"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getSession } from "@/lib/dal";
import { createClient } from "@/lib/supabase/server";

export type ActionResult<T = object> =
  | ({ ok: true } & T)
  | { ok: false; error: string };

const idsSchema = z.array(z.string().uuid());

/**
 * Marks the given notifications as read (idempotent).
 *
 * RLS scopes the update to the caller's own rows, and the read_at column
 * grant permits the write; we still confirm a session so unauthenticated
 * callers fail fast with a clear message. Rows that are already read are
 * skipped via `.is('read_at', null)` so the timestamp isn't churned.
 */
export async function markNotificationsRead(
  ids: string[],
): Promise<ActionResult> {
  const parsed = idsSchema.safeParse(ids);
  if (!parsed.success) {
    return { ok: false, error: "Invalid notification ids." };
  }

  // Nothing to do - avoid a pointless round-trip.
  if (parsed.data.length === 0) return { ok: true };

  const session = await getSession();
  if (!session) return { ok: false, error: "Not signed in." };

  const supabase = await createClient();
  // The `notifications` table type is generated by a migration applied in
  // parallel; cast the table accessor until database.types picks it up.
  const { error } = await (supabase.from("notifications") as unknown as {
    update: (values: { read_at: string }) => {
      in: (
        column: "id",
        values: string[],
      ) => {
        is: (
          column: "read_at",
          value: null,
        ) => Promise<{ error: { message: string } | null }>;
      };
    };
  })
    .update({ read_at: new Date().toISOString() })
    .in("id", parsed.data)
    .is("read_at", null);

  if (error) return { ok: false, error: error.message };

  revalidatePath("/notifications");
  return { ok: true };
}
