import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

// Server component: reads the caller's unread-notification count with a
// head-only exact count (RLS restricts the rows to the current user, so no
// explicit user filter is needed), then renders a bell that links to the
// notifications inbox with a small unread badge.
export async function NotificationBell() {
  const supabase = await createClient();

  // The `notifications` table type is generated by a migration applied in
  // parallel; cast the table accessor until database.types picks it up.
  const { count } = await (supabase.from("notifications") as unknown as {
    select: (
      columns: string,
      options: { count: "exact"; head: true },
    ) => {
      is: (
        column: "read_at",
        value: null,
      ) => Promise<{ count: number | null }>;
    };
  })
    .select("*", { count: "exact", head: true })
    .is("read_at", null);

  const unread = count ?? 0;
  const badge = unread > 9 ? "9+" : String(unread);

  return (
    <Link
      href="/notifications"
      aria-label={
        unread > 0
          ? `Notifications, ${unread} unread`
          : "Notifications"
      }
      className="relative flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-border-strong bg-card text-text-muted transition-colors duration-200 ease-standard hover:bg-muted hover:text-text focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        className="h-5 w-5"
        aria-hidden="true"
      >
        <path
          fillRule="evenodd"
          d="M10 2a6 6 0 0 0-6 6c0 1.887-.454 3.665-1.257 5.234a.75.75 0 0 0 .515 1.076 32.9 32.9 0 0 0 3.256.508 3.5 3.5 0 0 0 6.972 0 32.903 32.903 0 0 0 3.256-.508.75.75 0 0 0 .515-1.076A11.448 11.448 0 0 1 16 8a6 6 0 0 0-6-6ZM8.05 14.943a33.54 33.54 0 0 0 3.9 0 2 2 0 0 1-3.9 0Z"
          clipRule="evenodd"
        />
      </svg>
      {unread > 0 ? (
        <span
          aria-hidden="true"
          className="absolute -right-0.5 -top-0.5 flex min-w-4 items-center justify-center rounded-pill bg-red px-1 text-[10px] font-semibold leading-4 text-white"
        >
          {badge}
        </span>
      ) : null}
    </Link>
  );
}
