import type { Metadata } from "next";
import Link from "next/link";
import { verifySession } from "@/lib/dal";
import { createClient } from "@/lib/supabase/server";
import { MarkReadOnMount } from "./MarkReadOnMount";

export const metadata: Metadata = {
  title: "Notifications · HuskyMarkets",
};

// Local row shape - the `notifications` table type is generated by a migration
// applied in parallel, so we don't import it from database.types yet.
interface NotificationRow {
  id: string;
  user_id: string;
  type: "market_resolved" | "market_voided" | "market_approved" | "market_rejected";
  market_id: string | null;
  payload: Record<string, unknown>;
  read_at: string | null;
  email_status: string;
  email_sent_at: string | null;
  created_at: string;
}

/** Reads a payload field as a trimmed string, or null when absent/blank. */
function readString(
  payload: Record<string, unknown>,
  key: string,
): string | null {
  const value = payload[key];
  if (value === null || value === undefined) return null;
  const text = String(value).trim();
  return text.length > 0 ? text : null;
}

/** Builds the human-readable copy for a notification from its type + payload. */
function describeNotification(row: NotificationRow): string {
  const payload = row.payload ?? {};
  const title = readString(payload, "market_title") ?? "your market";
  const result = readString(payload, "result");
  const role = readString(payload, "role");
  const amount = readString(payload, "amount");
  const refund = readString(payload, "refund");

  if (row.type === "market_resolved") {
    if (result === "won") return `You won ${amount ?? "0"} HC on ${title}`;
    if (result === "lost") return `You lost ${amount ?? "0"} HC on ${title}`;
    if (result === "refunded") return `Stakes refunded on ${title}`;
    if (role === "creator") return `Your market resolved: ${title}`;
    return title;
  }

  if (row.type === "market_voided") {
    if (role === "bettor") {
      return `${refund ?? "0"} HC refunded - ${title} was voided`;
    }
    if (role === "creator") return `Your market was voided: ${title}`;
    return title;
  }

  if (row.type === "market_approved") {
    return `Your market was approved and is now live: ${title}`;
  }

  if (row.type === "market_rejected") {
    return `Your market was not approved: ${title}`;
  }

  return title;
}

export default async function NotificationsPage() {
  await verifySession();
  const supabase = await createClient();

  // The `notifications` table type is generated by a migration applied in
  // parallel; cast the table accessor until database.types picks it up.
  const { data } = await (supabase.from("notifications") as unknown as {
    select: (columns: string) => {
      order: (
        column: "created_at",
        options: { ascending: boolean },
      ) => {
        limit: (
          count: number,
        ) => Promise<{ data: NotificationRow[] | null }>;
      };
    };
  })
    .select("*")
    .order("created_at", { ascending: false })
    .limit(50);

  const notifications: NotificationRow[] = data ?? [];
  const unreadIds = notifications
    .filter((row) => row.read_at === null)
    .map((row) => row.id);

  return (
    <div className="mx-auto flex w-full max-w-2xl flex-col gap-8 py-8 sm:py-16">
      <MarkReadOnMount ids={unreadIds} />

      <div>
        <h1 className="text-3xl font-semibold text-text sm:text-4xl">
          Notifications
        </h1>
        <p className="mt-2 text-sm text-text-muted">
          Market resolutions and refunds show up here.
        </p>
      </div>

      {notifications.length === 0 ? (
        <div className="card-surface p-6 text-sm text-text-muted">
          No notifications yet.
        </div>
      ) : (
        <ul className="card-surface flex flex-col divide-y divide-hairline overflow-hidden">
          {notifications.map((row) => {
            const unread = row.read_at === null;
            const copy = describeNotification(row);

            const body = (
              <div className="flex items-start gap-3 p-4 sm:p-5">
                {unread ? (
                  <span
                    aria-hidden="true"
                    className="mt-1.5 size-2 shrink-0 rounded-pill bg-red"
                  />
                ) : (
                  <span
                    aria-hidden="true"
                    className="mt-1.5 size-2 shrink-0"
                  />
                )}
                <p
                  className={`text-sm ${
                    unread
                      ? "font-semibold text-text"
                      : "font-medium text-text-muted"
                  }`}
                >
                  {copy}
                </p>
              </div>
            );

            return (
              <li key={row.id}>
                {row.market_id ? (
                  <Link
                    href={`/market/${row.market_id}`}
                    className="block transition-colors duration-150 hover:bg-muted focus-visible:bg-muted focus-visible:outline-none"
                  >
                    {body}
                  </Link>
                ) : (
                  body
                )}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
